COLUMNS:
  male: int64
  age: int64
  education: float64
  currentSmoker: int64
  cigsPerDay: float64
  BPMeds: float64
  prevalentStroke: int64
  prevalentHyp: int64
  diabetes: int64
  totChol: float64
  sysBP: float64
  diaBP: float64
  BMI: float64
  heartRate: float64
  glucose: float64
  TenYearCHD: int64

TARGET_COLUMN:
  name: diabetes