
artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/PratikKujur/Heart-Disease-Prediction-End-to-End-Project-using-Logistic-Regression-/raw/refs/heads/main/heartdiseasedatset.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

